spring:
  application:
    name: paymentService

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update