spring:
  application:
    name: roomService



  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pg_management_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:pass@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

room:
  vacate:
    reminder:
      cron: ${ROOM_VACATE_REMINDER_CRON:0 0 9 * * *}
    auto:
      cron: ${ROOM_VACATE_AUTO_CRON:0 30 0 * * *}

