name: Audit Service Pipeline

on:
  pull_request:
    branches: [Master]
    paths:
      - 'audit-service/**'
      - 'common/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: audit-service

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install
      - run: npm run build --if-present